import assert from "node:assert/strict";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const CLI = join(ROOT, "bin", "sync.mjs");
const GENERATED_MARKER = "<!-- Generated by tanner-agent-standards. Do not edit directly. -->";

function createConsumer(t, eve) {
  const directory = mkdtempSync(join(tmpdir(), "tanner-agent-standards-"));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  const packageJson = { name: "fixture", version: "1.0.0", private: true };
  if (eve !== undefined) packageJson.tannerAgentStandards = { eve };
  writeFileSync(join(directory, "package.json"), `${JSON.stringify(packageJson, null, 2)}\n`);
  return directory;
}

function run(directory, command = "sync") {
  return spawnSync(process.execPath, [CLI, command], {
    cwd: directory,
    encoding: "utf8",
  });
}

function read(directory, path) {
  return readFileSync(join(directory, path), "utf8");
}

function write(directory, path, content) {
  const file = join(directory, path);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
}

function snapshot(directory, prefix = "") {
  const result = {};
  for (const entry of readdirSync(join(directory, prefix), { withFileTypes: true })) {
    const path = join(prefix, entry.name);
    if (entry.isDirectory()) Object.assign(result, snapshot(directory, path));
    else result[path] = read(directory, path);
  }
  return result;
}

const validEveConfig = () => ({
  directory: "agent/skills",
  skills: {
    "tanner-website-review": {
      bundle: ["tanner-quality-bar", "tanner-brand-voice"],
    },
  },
});

test("consumers without Eve configuration keep the existing behavior", (t) => {
  const directory = createConsumer(t);
  const result = run(directory);

  assert.equal(result.status, 0, result.stderr);
  assert.equal(existsSync(join(directory, "agent")), false);
  assert.doesNotMatch(result.stdout, /• Eve/);
  assert.match(result.stdout, /• skills\s+.+ → \.claude\/skills, \.cursor\/rules/);
  assert.doesNotMatch(result.stdout, /• Claude/);
  assert.equal(run(directory, "check").status, 0);
});

test("init does not add Eve configuration", (t) => {
  const directory = createConsumer(t);
  const before = read(directory, "package.json");

  assert.equal(run(directory, "init").status, 0);
  assert.equal(read(directory, "package.json"), before);
  assert.equal(existsSync(join(directory, "agent")), false);
});

test("sync renders a deterministic Eve skill with ordered bundles and local links", (t) => {
  const directory = createConsumer(t, validEveConfig());
  const result = run(directory);
  const outputPath = "agent/skills/tanner-website-review/SKILL.md";

  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /• Eve\s+→ agent\/skills\/tanner-website-review/);

  const output = read(directory, outputPath);
  const canonical = read(ROOT, "skills/tanner-website-review/SKILL.md");
  const canonicalFrontmatter = canonical.match(/^---\n[\s\S]*?\n---/)[0];
  assert.ok(output.startsWith(`${canonicalFrontmatter}\n\n${GENERATED_MARKER}\n\n`));
  assert.ok(
    output.indexOf("## Bundled Reference: Tanner Quality Bar") <
      output.indexOf("## Bundled Reference: Tanner Brand Voice"),
  );
  assert.equal((output.match(/^---$/gm) || []).length, 2);
  assert.doesNotMatch(output, /\[\[[a-z0-9-]+\]\]/);
  assert.match(output, /\[Tanner Quality Bar\]\(#bundled-reference-tanner-quality-bar\)/);
  assert.match(output, /\[Tanner Brand Voice\]\(#bundled-reference-tanner-brand-voice\)/);
  assert.match(output, /\[Tanner Website Review\]\(#tanner-website-review\)/);
  assert.match(output, /Tanner Code Review/);
  assert.ok(output.endsWith("\n"));
  assert.ok(!output.endsWith("\n\n"));

  const firstSnapshot = snapshot(directory);
  assert.equal(run(directory).status, 0);
  assert.deepEqual(snapshot(directory), firstSnapshot);
});

test("check passes after sync and fails after generated Eve output is edited", (t) => {
  const directory = createConsumer(t, validEveConfig());
  const outputPath = "agent/skills/tanner-website-review/SKILL.md";

  assert.equal(run(directory).status, 0);
  assert.equal(run(directory, "check").status, 0);

  write(directory, outputPath, `${read(directory, outputPath)}edited\n`);
  const drift = run(directory, "check");
  assert.equal(drift.status, 1);
  assert.match(drift.stderr, /Eve skill drift at agent\/skills\/tanner-website-review\/SKILL\.md/);
});

test("missing requested and bundled skills produce actionable errors before writing", async (t) => {
  await t.test("requested skill", (t) => {
    const directory = createConsumer(t, {
      directory: "agent/skills",
      skills: { "not-a-skill": { bundle: [] } },
    });
    const result = run(directory);
    assert.equal(result.status, 1);
    assert.match(result.stderr, /Unknown Eve skill "not-a-skill"/);
    assert.equal(existsSync(join(directory, "AGENTS.md")), false);
  });

  await t.test("bundled skill", (t) => {
    const directory = createConsumer(t, {
      directory: "agent/skills",
      skills: { "tanner-website-review": { bundle: ["not-a-skill"] } },
    });
    const result = run(directory);
    assert.equal(result.status, 1);
    assert.match(result.stderr, /Unknown bundled Eve skill "not-a-skill"/);
    assert.equal(existsSync(join(directory, "AGENTS.md")), false);
  });
});

test("absolute and traversal Eve directories are rejected", async (t) => {
  for (const [name, directoryPath] of [
    ["absolute", join(tmpdir(), "eve-skills")],
    ["traversal", "agent/../outside"],
    ["Windows absolute", "C:\\eve-skills"],
  ]) {
    await t.test(name, (t) => {
      const directory = createConsumer(t, {
        directory: directoryPath,
        skills: { "tanner-website-review": { bundle: [] } },
      });
      const result = run(directory);
      assert.equal(result.status, 1);
      assert.match(result.stderr, /use a repository-relative path without "\.\." traversal/);
      assert.equal(existsSync(join(directory, "AGENTS.md")), false);
    });
  }
});

test("sync removes only stale Eve files carrying the generated marker", (t) => {
  const directory = createConsumer(t, validEveConfig());
  const stalePath = "agent/skills/old-generated/SKILL.md";
  const staleAsset = "agent/skills/old-generated/notes.txt";
  const authoredPath = "agent/skills/user-authored/SKILL.md";
  write(directory, stalePath, `${GENERATED_MARKER}\n\nstale\n`);
  write(directory, staleAsset, "keep me\n");
  write(directory, authoredPath, "# User-authored skill\n");

  assert.equal(run(directory).status, 0);
  assert.equal(existsSync(join(directory, stalePath)), false);
  assert.equal(read(directory, staleAsset), "keep me\n");
  assert.equal(read(directory, authoredPath), "# User-authored skill\n");
});

test("check reports stale generated Eve output but ignores user-authored skills", (t) => {
  const directory = createConsumer(t, validEveConfig());
  assert.equal(run(directory).status, 0);
  write(directory, "agent/skills/stale/SKILL.md", `${GENERATED_MARKER}\n`);
  write(directory, "agent/skills/user-authored/SKILL.md", "# Mine\n");

  const result = run(directory, "check");
  assert.equal(result.status, 1);
  assert.match(result.stderr, /Stale generated Eve skill at agent\/skills\/stale\/SKILL\.md/);

  rmSync(join(directory, "agent/skills/stale"), { recursive: true });
  assert.equal(run(directory, "check").status, 0);
});
